# Generated by Django 4.2.5 on 2023-11-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_eventmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventModel',
            new_name='EventsModel',
        ),
    ]
