# Generated by Django 4.2.5 on 2023-11-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_rename_eventmodel_eventsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=30)),
                ('event_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='EventsModel',
        ),
    ]
