# Generated by Django 4.2.5 on 2023-12-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_neweventmodel_delete_eventsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='neweventmodel',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neweventmodel',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
