# Generated by Django 4.2.5 on 2023-12-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_neweventmodel_end_neweventmodel_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='hours_spent',
        ),
    ]
