# Generated by Django 4.2.5 on 2023-12-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_remove_taskmodel_hours_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neweventmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
