# Generated by Django 4.2.5 on 2023-12-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_neweventmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neweventmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
